/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherLessonPlannerRouteImport } from './routes/teacher.lesson-planner'
import { Route as TeacherCourseBuilderRouteImport } from './routes/teacher.course-builder'
import { Route as TeacherCommunicationsRouteImport } from './routes/teacher.communications'
import { Route as TeacherAssignmentReviewRouteImport } from './routes/teacher.assignment-review'
import { Route as TeacherAssessmentCreatorRouteImport } from './routes/teacher.assessment-creator'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentParentAssistantRouteImport } from './routes/student.parent-assistant'
import { Route as StudentLiveClassRouteImport } from './routes/student.live-class'
import { Route as StudentJobsRouteImport } from './routes/student.jobs'
import { Route as StudentHindiMentorRouteImport } from './routes/student.hindi-mentor'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentCoursePlayerRouteImport } from './routes/student.course-player'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentCareerPlanRouteImport } from './routes/student.career-plan'
import { Route as StudentAssignmentCheckRouteImport } from './routes/student.assignment-check'
import { Route as StudentAssessmentsRouteImport } from './routes/student.assessments'
import { Route as StudentAiMentorRouteImport } from './routes/student.ai-mentor'
import { Route as StudentAdaptiveQuizRouteImport } from './routes/student.adaptive-quiz'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLessonPlannerRoute = TeacherLessonPlannerRouteImport.update({
  id: '/lesson-planner',
  path: '/lesson-planner',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCourseBuilderRoute = TeacherCourseBuilderRouteImport.update({
  id: '/course-builder',
  path: '/course-builder',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCommunicationsRoute = TeacherCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentReviewRoute = TeacherAssignmentReviewRouteImport.update({
  id: '/assignment-review',
  path: '/assignment-review',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssessmentCreatorRoute =
  TeacherAssessmentCreatorRouteImport.update({
    id: '/assessment-creator',
    path: '/assessment-creator',
    getParentRoute: () => TeacherRoute,
  } as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentParentAssistantRoute = StudentParentAssistantRouteImport.update({
  id: '/parent-assistant',
  path: '/parent-assistant',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLiveClassRoute = StudentLiveClassRouteImport.update({
  id: '/live-class',
  path: '/live-class',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJobsRoute = StudentJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHindiMentorRoute = StudentHindiMentorRouteImport.update({
  id: '/hindi-mentor',
  path: '/hindi-mentor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursePlayerRoute = StudentCoursePlayerRouteImport.update({
  id: '/course-player',
  path: '/course-player',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCareerPlanRoute = StudentCareerPlanRouteImport.update({
  id: '/career-plan',
  path: '/career-plan',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentCheckRoute = StudentAssignmentCheckRouteImport.update({
  id: '/assignment-check',
  path: '/assignment-check',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiMentorRoute = StudentAiMentorRouteImport.update({
  id: '/ai-mentor',
  path: '/ai-mentor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAdaptiveQuizRoute = StudentAdaptiveQuizRouteImport.update({
  id: '/adaptive-quiz',
  path: '/adaptive-quiz',
  getParentRoute: () => StudentRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/student/adaptive-quiz': typeof StudentAdaptiveQuizRoute
  '/student/ai-mentor': typeof StudentAiMentorRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/assignment-check': typeof StudentAssignmentCheckRoute
  '/student/career-plan': typeof StudentCareerPlanRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/course-player': typeof StudentCoursePlayerRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/hindi-mentor': typeof StudentHindiMentorRoute
  '/student/jobs': typeof StudentJobsRoute
  '/student/live-class': typeof StudentLiveClassRoute
  '/student/parent-assistant': typeof StudentParentAssistantRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/assessment-creator': typeof TeacherAssessmentCreatorRoute
  '/teacher/assignment-review': typeof TeacherAssignmentReviewRoute
  '/teacher/communications': typeof TeacherCommunicationsRoute
  '/teacher/course-builder': typeof TeacherCourseBuilderRoute
  '/teacher/lesson-planner': typeof TeacherLessonPlannerRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/student/adaptive-quiz': typeof StudentAdaptiveQuizRoute
  '/student/ai-mentor': typeof StudentAiMentorRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/assignment-check': typeof StudentAssignmentCheckRoute
  '/student/career-plan': typeof StudentCareerPlanRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/course-player': typeof StudentCoursePlayerRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/hindi-mentor': typeof StudentHindiMentorRoute
  '/student/jobs': typeof StudentJobsRoute
  '/student/live-class': typeof StudentLiveClassRoute
  '/student/parent-assistant': typeof StudentParentAssistantRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/assessment-creator': typeof TeacherAssessmentCreatorRoute
  '/teacher/assignment-review': typeof TeacherAssignmentReviewRoute
  '/teacher/communications': typeof TeacherCommunicationsRoute
  '/teacher/course-builder': typeof TeacherCourseBuilderRoute
  '/teacher/lesson-planner': typeof TeacherLessonPlannerRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/student/adaptive-quiz': typeof StudentAdaptiveQuizRoute
  '/student/ai-mentor': typeof StudentAiMentorRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/assignment-check': typeof StudentAssignmentCheckRoute
  '/student/career-plan': typeof StudentCareerPlanRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/course-player': typeof StudentCoursePlayerRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/hindi-mentor': typeof StudentHindiMentorRoute
  '/student/jobs': typeof StudentJobsRoute
  '/student/live-class': typeof StudentLiveClassRoute
  '/student/parent-assistant': typeof StudentParentAssistantRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/assessment-creator': typeof TeacherAssessmentCreatorRoute
  '/teacher/assignment-review': typeof TeacherAssignmentReviewRoute
  '/teacher/communications': typeof TeacherCommunicationsRoute
  '/teacher/course-builder': typeof TeacherCourseBuilderRoute
  '/teacher/lesson-planner': typeof TeacherLessonPlannerRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/reports'
    | '/admin/schools'
    | '/student/adaptive-quiz'
    | '/student/ai-mentor'
    | '/student/assessments'
    | '/student/assignment-check'
    | '/student/career-plan'
    | '/student/certificates'
    | '/student/course-player'
    | '/student/courses'
    | '/student/hindi-mentor'
    | '/student/jobs'
    | '/student/live-class'
    | '/student/parent-assistant'
    | '/student/profile'
    | '/teacher/assessment-creator'
    | '/teacher/assignment-review'
    | '/teacher/communications'
    | '/teacher/course-builder'
    | '/teacher/lesson-planner'
    | '/teacher/reports'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/reports'
    | '/admin/schools'
    | '/student/adaptive-quiz'
    | '/student/ai-mentor'
    | '/student/assessments'
    | '/student/assignment-check'
    | '/student/career-plan'
    | '/student/certificates'
    | '/student/course-player'
    | '/student/courses'
    | '/student/hindi-mentor'
    | '/student/jobs'
    | '/student/live-class'
    | '/student/parent-assistant'
    | '/student/profile'
    | '/teacher/assessment-creator'
    | '/teacher/assignment-review'
    | '/teacher/communications'
    | '/teacher/course-builder'
    | '/teacher/lesson-planner'
    | '/teacher/reports'
    | '/teacher/students'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/reports'
    | '/admin/schools'
    | '/student/adaptive-quiz'
    | '/student/ai-mentor'
    | '/student/assessments'
    | '/student/assignment-check'
    | '/student/career-plan'
    | '/student/certificates'
    | '/student/course-player'
    | '/student/courses'
    | '/student/hindi-mentor'
    | '/student/jobs'
    | '/student/live-class'
    | '/student/parent-assistant'
    | '/student/profile'
    | '/teacher/assessment-creator'
    | '/teacher/assignment-review'
    | '/teacher/communications'
    | '/teacher/course-builder'
    | '/teacher/lesson-planner'
    | '/teacher/reports'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/lesson-planner': {
      id: '/teacher/lesson-planner'
      path: '/lesson-planner'
      fullPath: '/teacher/lesson-planner'
      preLoaderRoute: typeof TeacherLessonPlannerRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/course-builder': {
      id: '/teacher/course-builder'
      path: '/course-builder'
      fullPath: '/teacher/course-builder'
      preLoaderRoute: typeof TeacherCourseBuilderRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/communications': {
      id: '/teacher/communications'
      path: '/communications'
      fullPath: '/teacher/communications'
      preLoaderRoute: typeof TeacherCommunicationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignment-review': {
      id: '/teacher/assignment-review'
      path: '/assignment-review'
      fullPath: '/teacher/assignment-review'
      preLoaderRoute: typeof TeacherAssignmentReviewRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assessment-creator': {
      id: '/teacher/assessment-creator'
      path: '/assessment-creator'
      fullPath: '/teacher/assessment-creator'
      preLoaderRoute: typeof TeacherAssessmentCreatorRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/parent-assistant': {
      id: '/student/parent-assistant'
      path: '/parent-assistant'
      fullPath: '/student/parent-assistant'
      preLoaderRoute: typeof StudentParentAssistantRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/live-class': {
      id: '/student/live-class'
      path: '/live-class'
      fullPath: '/student/live-class'
      preLoaderRoute: typeof StudentLiveClassRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/jobs': {
      id: '/student/jobs'
      path: '/jobs'
      fullPath: '/student/jobs'
      preLoaderRoute: typeof StudentJobsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/hindi-mentor': {
      id: '/student/hindi-mentor'
      path: '/hindi-mentor'
      fullPath: '/student/hindi-mentor'
      preLoaderRoute: typeof StudentHindiMentorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course-player': {
      id: '/student/course-player'
      path: '/course-player'
      fullPath: '/student/course-player'
      preLoaderRoute: typeof StudentCoursePlayerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/career-plan': {
      id: '/student/career-plan'
      path: '/career-plan'
      fullPath: '/student/career-plan'
      preLoaderRoute: typeof StudentCareerPlanRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignment-check': {
      id: '/student/assignment-check'
      path: '/assignment-check'
      fullPath: '/student/assignment-check'
      preLoaderRoute: typeof StudentAssignmentCheckRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-mentor': {
      id: '/student/ai-mentor'
      path: '/ai-mentor'
      fullPath: '/student/ai-mentor'
      preLoaderRoute: typeof StudentAiMentorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/adaptive-quiz': {
      id: '/student/adaptive-quiz'
      path: '/adaptive-quiz'
      fullPath: '/student/adaptive-quiz'
      preLoaderRoute: typeof StudentAdaptiveQuizRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAdaptiveQuizRoute: typeof StudentAdaptiveQuizRoute
  StudentAiMentorRoute: typeof StudentAiMentorRoute
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentAssignmentCheckRoute: typeof StudentAssignmentCheckRoute
  StudentCareerPlanRoute: typeof StudentCareerPlanRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCoursePlayerRoute: typeof StudentCoursePlayerRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentHindiMentorRoute: typeof StudentHindiMentorRoute
  StudentJobsRoute: typeof StudentJobsRoute
  StudentLiveClassRoute: typeof StudentLiveClassRoute
  StudentParentAssistantRoute: typeof StudentParentAssistantRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAdaptiveQuizRoute: StudentAdaptiveQuizRoute,
  StudentAiMentorRoute: StudentAiMentorRoute,
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentAssignmentCheckRoute: StudentAssignmentCheckRoute,
  StudentCareerPlanRoute: StudentCareerPlanRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCoursePlayerRoute: StudentCoursePlayerRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentHindiMentorRoute: StudentHindiMentorRoute,
  StudentJobsRoute: StudentJobsRoute,
  StudentLiveClassRoute: StudentLiveClassRoute,
  StudentParentAssistantRoute: StudentParentAssistantRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssessmentCreatorRoute: typeof TeacherAssessmentCreatorRoute
  TeacherAssignmentReviewRoute: typeof TeacherAssignmentReviewRoute
  TeacherCommunicationsRoute: typeof TeacherCommunicationsRoute
  TeacherCourseBuilderRoute: typeof TeacherCourseBuilderRoute
  TeacherLessonPlannerRoute: typeof TeacherLessonPlannerRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssessmentCreatorRoute: TeacherAssessmentCreatorRoute,
  TeacherAssignmentReviewRoute: TeacherAssignmentReviewRoute,
  TeacherCommunicationsRoute: TeacherCommunicationsRoute,
  TeacherCourseBuilderRoute: TeacherCourseBuilderRoute,
  TeacherLessonPlannerRoute: TeacherLessonPlannerRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
